name: Deploy Medicine Prescription Analyzer

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug mode'
        required: false
        default: 'false'

env:
  AWS_REGION: us-east-1
  TERRAFORM_VERSION: 1.5.0

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Debug Info
      run: |
        echo "🔍 Workflow triggered successfully!"
        echo "Branch: ${{ github.ref }}"
        echo "Event: ${{ github.event_name }}"
        echo "Repository: ${{ github.repository }}"
        echo "Commit: ${{ github.sha }}"

  test:
    needs: debug
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build frontend
      run: npm run build
    
    - name: Test Lambda function syntax
      run: |
        python3 -m py_compile lambda/prescription-analyzer.py

  deploy-infrastructure:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}
        terraform_wrapper: false
    
    - name: Prepare Lambda deployment package
      run: |
        cd lambda
        zip -r ../terraform/prescription_analyzer.zip . -x "*.pyc" "__pycache__/*"
        ls -la ../terraform/  # Verify zip file was created
    
    - name: Terraform Init
      run: |
        cd terraform
        terraform init
        echo "✅ Terraform initialized successfully"
    
    - name: Terraform Plan
      run: |
        cd terraform
        terraform validate
        echo "✅ Terraform configuration is valid"
    
    - name: Terraform Plan
      run: |
        cd terraform
        terraform plan -out=tfplan
        echo "✅ Terraform plan completed successfully"
    
    - name: Terraform Apply
      run: |
        cd terraform
        terraform apply -auto-approve tfplan
        echo "✅ Infrastructure deployed successfully"
    
    - name: Get Terraform Outputs
      id: terraform-outputs
      run: |
        cd terraform
        echo "api_url=$(terraform output -raw api_gateway_invoke_url)" >> $GITHUB_OUTPUT
        echo "s3_bucket=$(terraform output -raw website_bucket_name)" >> $GITHUB_OUTPUT
        echo "cloudfront_url=$(terraform output -raw cloudfront_url)" >> $GITHUB_OUTPUT
        echo "prescription_bucket=$(terraform output -raw s3_bucket_name)" >> $GITHUB_OUTPUT
        
        # Display outputs for verification
        echo "🚀 Deployment Outputs:"
        echo "API Gateway URL: $(terraform output -raw api_gateway_invoke_url)"
        echo "Website S3 Bucket: $(terraform output -raw website_bucket_name)"
        echo "CloudFront URL: $(terraform output -raw cloudfront_url)"
        echo "Prescription S3 Bucket: $(terraform output -raw s3_bucket_name)"
    
    outputs:
      api_url: ${{ steps.terraform-outputs.outputs.api_url }}
      s3_bucket: ${{ steps.terraform-outputs.outputs.s3_bucket }}
      cloudfront_url: ${{ steps.terraform-outputs.outputs.cloudfront_url }}
      prescription_bucket: ${{ steps.terraform-outputs.outputs.prescription_bucket }}

  deploy-frontend:
    needs: deploy-infrastructure
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Update API configuration
      run: |
        sed -i "s|https://your-api-gateway-url.amazonaws.com/prod/analyze|${{ needs.deploy-infrastructure.outputs.api_url }}/analyze|g" script.js
        sed -i "s|your-prescription-bucket|${{ needs.deploy-infrastructure.outputs.prescription_bucket }}|g" script.js
        echo "✅ Configuration updated with actual AWS endpoints"
    
    - name: Build frontend
      run: npm run build
       echo "✅ Frontend built successfully"
    
    - name: Deploy to S3
      run: |
        aws s3 sync dist/ s3://${{ needs.deploy-infrastructure.outputs.s3_bucket }}/ --delete
        echo "✅ Frontend deployed to S3"
    
    - name: Invalidate CloudFront
      run: |
        DISTRIBUTION_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?Origins.Items[0].DomainName=='${{ needs.deploy-infrastructure.outputs.s3_bucket }}.s3.amazonaws.com'].Id" --output text)
        if [ ! -z "$DISTRIBUTION_ID" ]; then
          aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
          echo "✅ CloudFront cache invalidated"
        else
          echo "⚠️ CloudFront distribution not found, skipping invalidation"
        fi
    
    - name: Display URLs
      run: |
        echo "🚀 Deployment completed!"
        echo "📱 Frontend URL: ${{ needs.deploy-infrastructure.outputs.cloudfront_url }}"
        echo "🔗 API URL: ${{ needs.deploy-infrastructure.outputs.api_url }}"
        echo "📦 Prescription Bucket: ${{ needs.deploy-infrastructure.outputs.prescription_bucket }}"
        echo ""
        echo "🎯 Next Steps:"
        echo "1. Visit the CloudFront URL to test the application"
        echo "2. Upload a prescription image to test the full pipeline"
        echo "3. Check CloudWatch logs if you encounter any issues"