name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Type "destroy" to confirm infrastructure destruction'
        required: true
        default: ''

env:
  AWS_REGION: us-east-1
  TERRAFORM_VERSION: 1.5.0

jobs:
  destroy-infrastructure:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm_destroy == 'destroy'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}
        terraform_wrapper: false
    
    - name: Prepare Lambda deployment package
      run: |
        cd lambda
        zip -r ../terraform/prescription_analyzer.zip . -x "*.pyc" "__pycache__/*"
    
    - name: Terraform Init
      run: |
        cd terraform
        terraform init
    
    - name: Empty S3 Buckets Before Destroy
      run: |
        cd terraform
        # Get bucket names from terraform state
        WEBSITE_BUCKET=$(terraform output -raw website_bucket_name 2>/dev/null || echo "")
        PRESCRIPTION_BUCKET=$(terraform output -raw s3_bucket_name 2>/dev/null || echo "")
        
        if [ ! -z "$WEBSITE_BUCKET" ]; then
          echo "Emptying website bucket: $WEBSITE_BUCKET"
          aws s3 rm s3://$WEBSITE_BUCKET --recursive || true
        fi
        
        if [ ! -z "$PRESCRIPTION_BUCKET" ]; then
          echo "Emptying prescription bucket: $PRESCRIPTION_BUCKET"
          aws s3 rm s3://$PRESCRIPTION_BUCKET --recursive || true
        fi
    
    - name: Terraform Destroy
      run: |
        cd terraform
        terraform destroy -auto-approve
        echo "🗑️ Infrastructure destroyed successfully"
    
    - name: Cleanup Confirmation
      run: |
        echo "✅ All AWS resources have been destroyed"
        echo "💰 This will stop incurring AWS charges"
        echo "⚠️ All data in S3 buckets has been permanently deleted"